### ISSUE TITLE
Macros duplicated

### ISSUE THREAD

**Issue by trying-to-function** [tg123/myslot#16] opened 2022-02-01 23:54 UTC
Addons that create macros end up getting duplicated via myslot. Anyway to stop this?

**Comment by tg123** [comment] 2022-02-02 00:45
`duplicate macro` is considered as bug
you can share the exported text or email it to me, i can take a look

**Comment by kephjs** [comment] 2023-02-17 20:43
It might be a user error. I am using myslot for a long time and I've had problems with myslot duplicating macros aswell.
OP hasn't explained his issue clearly, so he might not be using the "Clear all macros" option when importing another profile. Afterwards he might save that profile and voila he duplicated his macros.

**Comment by tg123** [comment] 2023-02-18 07:05
@kephjs  please share the exported text, I will check if duplicate macro inside

**Comment by matthewmerendo** [comment] 2023-08-19 00:23
Any more information about this? I'm having two issues with macros and myslot:

- I use an addon called Buffet that creates dynamic macros food, drinks, and potions. Myslot duplicates these account-wide macros.
- I use a single file for each class, symlinked across my toons, so that if I update a druid macro, it updates the macro on all my druids. These seem fine with myslot, but I wanted to make the premise known.

The duplication is quite annoying, and I'm hoping we have already found a solution!

**Comment by tg123** [comment] 2023-08-19 09:45
myslot will do dedup for macro when importing
i need to check exported text to see when dedup is not working

what do you mean by `symlinked `, linux?

**Comment by matthewmerendo** [comment] 2023-08-19 18:55
Yes, a symlink like on Linux, though I am on a Windows machine. Basically I have a single file for all my priest macros, and then all my priests' macro.txt files just symlink to that main priest macro file.

As far as the deduping, I think the problem is that Buffet is dynamic, so it changes the single macro based on the items available to each character. So if my first character has Item A but my second character does not, and I do an import on my second character, there's nothing to de-dupe because they are technically different macros.

**Comment by tg123** [comment] 2024-06-29 11:47
should be fixed in latest version

**Closed by tg123** 2024-06-29 11:47 UTC
